### ISSUE TITLE
TODO before 2024.11.11

### ISSUE THREAD

**Issue by ivorkchan** [StockSim/StockSim#11]
# Due 2024.11.11

- [x] Implement `ExecuteBuy` use case
- [x] Implement **tests** for `ExecuteBuy` use case
- [ ] Implement view framework
- [x] Use cases described for each **user story** and user interations identified
- [x] **Wire frames** for all views sketched
- [x] Be able to make calls to the **API** your team has chosen
- [x] Prepare a minimal demo

**Comment by TheGreatCorrine** [comment]
APIs: Finnhub/Alpha Vintage
