### ISSUE TITLE
TODO(before Fri 15 Nov)

### ISSUE THREAD

**Issue by TheGreatCorrine** [StockSim/StockSim#34]
Meetings in the next week:
1. Mon 11 Nov, 3 PM -6 PM
2. Fri 15 Nov, 
3. Sat 16 Nov, 

- [ ] Assign one use case to each person, with at least one unit test per Interactor
- [ ] Update UML  @Raine-Yang-UofT 
- [ ] Update User Stories in README.md
- [ ] All View and View Model code written except for actionPerformed methods
- [ ] Pair program for this so that two people know the details of each View and View Model.
- [ ] In-memory data access objects created although perhaps not yet implemented to facilitate testing
- [ ] Builder written that creates the views — run the program and make sure each view looks okay (you might edit the build method between runs to show a different view or create multiple main classes / methods)
