### ISSUE TITLE
TODO(Before Mon Nov 18)

### ISSUE THREAD

**Issue by TheGreatCorrine** [StockSim/StockSim#56]
- [x] Change JTextField to JPasswordField
- [x] View -> Panel, add listener, Interactor e -> Presenter (ViewManager broadcast)
- [x] ValidationException
- [ ] Update the users' information in the database after each transaction
- [ ] Complete both presenters in buy/sell @TheGreatCorrine
- [ ] increase test coverage @all
- [ ] individual contribution
- [ ] presentation - clean architecture/Q&A/Professor Office Hour

Monday, ask how to write the transaction history test cases.

Implement the logout use case.

Ask what 100% test coverage is.
