### ISSUE TITLE
[TODO]Before Fri Nov 22

### ISSUE THREAD

**Issue by TheGreatCorrine** [StockSim/StockSim#65]
# Due date (eg. 2024.11.22)

## Tasks

1. Database (NoSQL like MongoDB or SQL)
2. Error messages in Presenters
3. Accessibility-related features
4. Tests of all interactors

## Meeting Time

1. 2024.11.22, 7 PM

## Notes

- [ ] Update documents - Finnhub in the initial handout, the blueprint, and ... (some docs I did not notice)
- [ ] Update README.md
- [x] Change JTextField to JPasswordField
- [x] View -> Panel, add listener, Interactor e -> Presenter (ViewManager broadcast)
- [x] ValidationException
- [ ] Update the users' information in the database after each transaction
- [ ] Complete both presenters in buy/sell @TheGreatCorrine
- [ ] increase test coverage @all
- [ ] individual contribution
- [ ] presentation - clean architecture/Q&A/Professor Office Hour

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added error messages for insufficient balance, stock not found, and validation exceptions in ExecuteBuyPresenter. Enhanced ExecuteBuyInteractorTest with additional test cases for error scenarios.

You can review changes in this commit: https://github.com/lattaai13/StockSim-StockSim-65/commit/0680818447182df96cf2ad6f1adda7691eea7bbd.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
