### ISSUE TITLE
[TODO] Before Mon Nov 25

### ISSUE THREAD

**Issue by TheGreatCorrine** [StockSim/StockSim#77]
# Due date

## Tasks

- [ ]  Ask the teaching assistant about the accessibility part
- [ ] Check Project README file @thqi3541 @AngelChen09 

## Slides 

On Monday, follow the template and the sample, and complete the presentation.
- [ ] Specification @TheGreatCorrine 
- [ ] Design SOLID / Clean Architecture
- [ ] Functionality Demonstration 4 mins @TheGreatCorrine 
On Monday, make a recording of the working version of the program, make a simpler version and a more complex version
- [ ] Code Organization 30 secs @ivorkchan package layer screenshot
- [ ] Code Quality 30 secs @Raine-Yang-UofT 
- [ ] Accessibility Report 
- [ ] Readme + The End (highlights) @thqi3541 / @TheGreatCorrine
